[package]
name = "lc3_sim"
version = "0.1.0"
authors = ["Brian Su"]
edition = "2021"

[dependencies]
byteorder = "1.4.3"
termios = "0.3.1"
structopt = "0.3.22"
winapi = "0.3.9"
winapi-i686-pc-windows-gnu = "0.4.0"
winapi-x86_64-pc-windows-gnu = "0.4.0"